name: Scanner Fortify

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      # Check out source code
      - name: Check Out Source Code
        uses: actions/checkout@v4

      # Java is required to run the various Fortify utilities. Ensuring proper version is installed on the runner.
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests
      - name: Package with ScanCentral
        run: |
          curl -L -o scancentral.zip https://github.com/fortify/scancentral/releases/download/v25.4.0/scancentral-client.zip
          unzip scancentral.zip -d scancentral
          ./scancentral/bin/scancentral package -o package.zip -mvn -exclude target,test,node_modules

      # Perform Fortify on Demand SAST + SCA scan and import SAST results into GitHub code scanning alerts
      - name: Run Fortify on Demand SAST & SCA Scan
        uses: fortify/github-action@v2
        with:
          sast-scan: true
          debricked-sca-scan: true
        env:
          FOD_URL: https://trial.fortify.com
          FOD_TENANT: ${{secrets.FOD_TENANT}}
          FOD_USER: ${{secrets.FOD_USER}}
          FOD_PASSWORD: ${{secrets.FOD_PAT}}
          FOD_RELEASE: 251853
          DO_EXPORT: true
          DO_SETUP: true
          DO_JOB_SUMMARY: true
          DO_PR_COMMENT: true
          #DO_POLICY_CHECK: true